function mainGUI
    clear all;
    close all;

    Fig1 = figure('Name','Proiect Sisteme de Comunicatii',... 
        'Units','normalized',...
        'Position',[0.2 0.2 0.6 0.4],...
        'NumberTitle','off','Color','#a2d8fc');  % fundal albastru deschis

    f=uimenu('Label','Proiect Sisteme de Comunicatii');
        
         uimenu(f,'Label','Documentatie','Callback','open(''Documentatie.pdf'')'); 
         uimenu(f,'Label','Bibliografie','Callback','open(''Bibliografie.pdf'')');
         uimenu(f,'Label','Iesire','Callback','close',...
                    'Separator','on','Accelerator','Q');

    % Tema sus, centru
    uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'Position', [0.1 0.7 0.8 0.2], ...
              'BackgroundColor','#a2d8fc', ...
              'ForegroundColor', '#001f4d', ...
              'String', 'Tema: Analyze Communication Link for Aircraft over Seawater Using Ray Tracing', ...
              'FontSize', 20, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');

    % Buton START in mijloc
    uicontrol('Style','pushbutton',...
              'Units','normalized',...
              'Position',[0.35 0.4 0.3 0.15],...
              'BackgroundColor','#a2d8fc', ...
              'FontSize',16,...   
              'ForegroundColor','black', ...
              'FontWeight','bold', ...
              'String','START',...
              'Callback','startSecondInterface'); 

    % Numele studentelor jos, centru
    uicontrol('Style','text',...
              'Units','normalized', ...
              'Position',[0.1 0.1 0.8 0.1], ...
              'BackgroundColor','#a2d8fc', ...
              'FontSize',14,...
              'ForegroundColor','#001f4d', ...
              'String','Studente: Pirlac Sabina Elena, Pop Andrada Iulia', ...
              'HorizontalAlignment','center');

 
end